### ISSUE TITLE
S3 example ?

### ISSUE THREAD

**Issue by frederic-joventures** [edasque/cloudwatch2graphite#15]
Hello,
I am curious to know if you were able to get cloudwatch S3 metrics from cloudwatch.
I cannot get any data from S3 (no problem with sqs, rds, ...)

Here is an example
```json
{

  "awsCredentials": {
    "accessKeyId": "KEY",
    "secretAccessKey": "SECRET",
    "region": "us-east-1"
  },

  "metricsConfig": {
    "metrics": [
      {
        "Namespace": "AWS/S3",
        "MetricName": "BucketSizeBytes",
        "Period": 60,
        "Statistics": [
          "Average"
        ],
        "Dimensions": [
        {
          "Name": "BucketName",
          "Value": "BUCKET_NAME"
        },
        {
            "Name": "StorageType",
            "Value": "StandardStorage"
        }
        ]
      }

    ],
    "carbonNameSpacePrefix": "cloudwatch2graphite"
  }
}
```

**Comment by edasque** [comment]
If I recall correctly back when I wrote this S3 didn't offer Cloudwatch metrics. Now they do (as documented in http://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html). I haven't had a need to retrieve S3 metrics but I see no reason why this wouldn't work. Maybe someone can give it a try to help you out?

**Comment by echadmiyodea** [comment]
Hi,

Your json seems to be fine, however the problem can be fixed by adding a small change into the main script:
then.setHours(then.getHours() - 72 // three days back
options["Period"] = '86400' // period of 24 hours

this will cause to collect data points from last 3 days, pay attention that cloudwatch takes the measurement only once a day.
